### ISSUE TITLE
add voxel contributors to the voxel github organization

### ISSUE THREAD

**Issue by maxogden** [voxel/issues#1]
mostly so that people can choose to publicize their membership and show off the voxel logo on their github profile!

**Comment by deathcap** [comment]
@kumavis @maxogden may I be added?

**Comment by kumavis** [comment]
I dont have auth

**Comment by deathcap** [comment]
:( @maxogden @andreypopp @bmeck @chrisdickinson @codemiller @cryptoquick @englercj @flyswatter @Goutte @Harrison-M @hughsk @incompl @jaekwon @jlord @kumavis @maxogden @melaniecebula @mikolalysenko @nakedible @pauln @ryanramage @shama @snagy @substack @tatarize @timoxley @troffmo5 @vladikoff @vogonistic @YenTheFirst anyone have access to the https://github.com/voxel organization mind adding me? Would like to https://github.com/voxel/issues/issues/7 Move more projects into voxel organization

**Comment by englercj** [comment]
@maxogden Is the only owner of that organization

**Comment by cryptoquick** [comment]
@deathcap thank you for keeping the dream alive
#voxelfuture

**Comment by kumavis** [comment]
well now its a party

![image](https://cloud.githubusercontent.com/assets/1474978/7437995/4bbf68f8-f012-11e4-80d8-c9e10c565cd5.png)

**Comment by deathcap** [comment]
maxogden added me thanks =)
If anyone else wants to be added let me know
