### ISSUE TITLE
Is there a demo of voxel.js running on Android?

### ISSUE THREAD

**Issue by mentiflectax** [voxel/issues#9]
According to [this article](http://venturebeat.com/2013/01/19/this-22-day-old-open-source-minecraft-cloning-game-builder-runs-in-javascript-in-your-browser/) voxel.js may be compatible with Android. If so, is there any demo I could try out on my Android phone?

**Comment by deathcap** [comment]
You could try the old three.js-based demo http://maxogden.github.io/voxel-hello-world/ but unfortunately it appears to have broken somehow https://github.com/maxogden/voxel-hello-world/issues/25#issuecomment-94984115 - alternatively try http://voxel.github.io/voxel-example/ (voxel-engine-stackgl based) but I haven't tested it on Android, if you do I'd be interested in the results. Haven't really focused on mobile browser support yet. I did try voxel-engine-stackgl on iPhone a while ago but it quickly ran out of memory, may need to adopt a smaller subset of WebGL for mobile graphics engines and further optimize texture loading etc. As well as the touch interface, see: https://github.com/voxel/issues/issues/2 mobile browser support

**Comment by mentiflectax** [comment]
Thanks for you answer.

If I open http://voxel.github.io/voxel-example/ in Chrome on my Android phone, I get the error message

> You need WebGL and Pointer Lock (Chrome 23/Firefox 14) to play this game. Click here for more information

Here is a [screenshot](http://i.imgur.com/DblMXi0.png).

Do you have any idea on how much effort it is to fix this problem?

**Comment by annyanich** [comment]
I know it's been a while, but just in case anyone comes looking for info on this like me, I found that http://voxel.github.io/voxel-example/ loads and seems to work fine on my second generation Nexus 7. 

For a second might not see anything, but then you will realize the player is falling down from the sky to the ground.  Seems perfectly smooth, like 60 fps. The only problem is there's no way to interact with it.

**Comment by mentiflectax** [comment]
Thanks for your comment, @annyanich . Then it's probably the old version of Android that's causing the problems on my phone.
